version: "3.0"

services:
  usersdb:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=something
  user-service:
    image: user-service
    ports:
      - 4030:8080
    environment:
      - MYSQL_ENDPOINT="129.221.79.199"

